logging:
  level:
    com:
      mpds:
        flinkautoscaler: debug
    org:
      springframework:
        data:
          r2dbc: debug
#        r2dbc: DEBUG
r2dbc:
  postgres:

    database: postgres
    hostname: localhost
    password: postgres
    port: 5432
    username: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
# Kafka config
kafka:
#  bootstrap-server: localhost:9092
  bootstrap-server: 35.246.217.71:31090
  st-prediction-topic: st-prediction
  lt-prediction-topic: lt-prediction
  topic: metric
  client-id-config: flink-autoscaler
  acks-config: all
metrics-server:
  prometheus:
    base-url: http://35.246.217.71:30090
    source-topic: covid
autoscaler:
  flink:
    base-url: http://35.198.125.206:8081
    job-id: f9ac965311173844c5a76bcc2b468d9a
    jar-id: a6a66646-eebd-4adf-8630-0fbe53d283a9_covid-engine-2.3.2.jar
    program-args: --statebackend.default false --checkpoint hdfs://hadoop-hdfs-namenode:8020/flink/checkpoints --checkpoint.interval 300000
    savepoint-directory: hdfs://hadoop-hdfs-namenode:8020/flink/savepoints
    cooldown-duration: 120
spring:
  cloud:
    stream:
      function:
        definition: metrics;shortTermPredictions;longTermPredictions
        bindings:
          metrics-in-0: prometheus-metrics
          shortTermPredictions-in-0: short-term-predictions
          longTermPredictions-in-0: long-term-predictions
      kafka:
        binder:
          brokers: 35.246.217.71:31090
#          brokers: localhost:9092
      bindings:
        prometheus-metrics:
          destination: metric
          group: autoscaling-group
          content-type: application/json
        short-term-predictions:
          destination: short-term-predictions
          group: st-autoscaling-group
          content-type: application/json
        long-term-predictions:
          destination: long-term-predictions
          group: lt-autoscaling-group
          content-type: application/json
