logging:
  level:
    com:
      mpds:
        flinkautoscaler: debug
    org:
      springframework:
        data:
          r2dbc: debug
r2dbc:
  postgres:
    database: postgres
    hostname: localhost
    password: postgres
    port: 5432
    username: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
# Kafka config
kafka:
  bootstrap-server: localhost:9092
  st-prediction-topic: st-prediction
  lt-prediction-topic: lt-prediction
  topic: metric
  client-id-config: flink-autoscaler
  acks-config: all
metrics-server:
  prometheus:
    base-url: http://34.107.94.158:30090
    query-path: /api/v1/query

spring:
  cloud:
    stream:
      function:
        bindings:
          prediction-in-0: input
      kafka:
        binder:
          brokers: localhost
      bindings:
        input:
          destination: prediction
          group: flink-autoscaler
          content-type: application/json

