kafka:
    ip: 35.246.236.92:31090
    # metric
    in_topic: metric
    # long-term-predictions
    out_topic: long-term-predictions
    input_interval: 10
    avg_agg_len: 1
    expected_period: 12
    # False
    self_simulate: False
    # False
    save_data: True
model:
    # 256
    seq_len: 64
    # 32
    pred_len: 16
    # 16
    hidden_dim: 16
    # 64
    memory_dim: 64
    # 1
    order: 1
train:
    # 5
    time: 7
    # 100
    buffer: 5
    # 0.001
    LR: 0.001
    pretrain_iters: 300