kafka:
    ip: 35.246.173.215:30002
    in_topic: metric 
    out_topic: prediction_lt
    input_interval: 10
    avg_agg_len: 1
    expected_period: 100
    self_simulate: True
model:
    seq_len: 64
    pred_len: 32
    cell: GRU
    hidden_dim: 16
    stack: 3
train:
    time: 5
    buffer: 50
    LR: 0.001
    pretrain_iters: 100
