kafka:
    ip: 127.0.0.1
    in_topic: statistics 
    out_topic: long-term-prediction
    input_interval: 0.1
    avg_agg_len: 1
    expected_period: 100
    self_simulate: True
model:
    seq_len: 128
    pred_len: 64
    cell: GRU
    hidden_dim: 16
    stack: 3
train:
    time: 5
    buffer: 100
    LR: 0.001
    pretrain_iters: 100
